### ISSUE TITLE
Fallback to JSON file if node is not present

### ISSUE THREAD

**Issue by FourierTransformer** [nvim-neorocks/luarocks-build-treesitter-parser#39]
Hello!

Thanks for putting this out there, it really elevated being able to use tree-sitter grammars in Lua! We're using your `tree-sitter-teal` for the teal language server to great effect!

So I made the tree-sitter CLI [installable via LuaRocks](https://github.com/FourierTransformer/tree-sitter-cli), and for folks who _don't_ have node installed, I think you can still run a `tree-sitter generate` if the JSON file is present and then `tree-sitter build` to compile the parser. I'll be honest I'm not sure if there are any edge cases there, but it appears to work for the teal grammar.

We're trying to get the teal-language-server to be fully installable via LuaRocks without any external dependencies, but right now it requires Node. I think it would be nice to fallback to using the JSON file if node is not installed and the JSON file is present. And if it fails, indicate that installing Node should solve the issue. It seems that a lot of the tree-sitter's do have grammar.json checked in, so I think it _could_ work.

Alternatively, slightly changing the code so that the `generate_from_json` doesn't require node would also work (caveat again being I'm not sure if there are edge cases).

Curious what your folks' thoughts are on this, and apologies if this request is waaaay out there.

**Comment by mrcjkb** [comment]
Hey :wave: 
thanks for the nice words. Sounds like a cool project you're working on!
I think what you're proposing sounds reasonable. It's possible that newer tree-sitter versions support `tree-sitter generate` without node. We'd have to check that and then potentially implement a fallback if the tree-sitter version matches the version that supports it.
At the moment, I'm quite busy with other stuff, particularly, [our own implementation of a luarocks client](https://github.com/nvim-neorocks/rocks) that I plan to add built-in support for tree-sitter parsers to (perhaps using the tree-sitter crate as a dependency).
So I might implement it there first.
Of course, PRs here are always welcome :smile:
